import { FileProvider } from './components/file-content';
import './global.css';

export const metadata = {
  title: 'Welcome to webapp',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <FileProvider>{children}</FileProvider>
      </body>
    </html>
  );
}
