api:
  replicaCount: 1
  image:
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3000

frontend:
  replicaCount: 1
  image:
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 4200

ingress:
  enabled: true
  className: "nginx"
  hosts:
    api: "api.enclaveid.com"
    frontend: "app.enclaveid.com"
  tls:
    enabled: true
    secretName: "enclaveid-tls"

ingress-nginx:
  enabled: true

cert-manager:
  enabled: true
  installCRDs: true
