api:
  replicaCount: 1
  image:
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

frontend:
  replicaCount: 1
  image:
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80

ingress:
  enabled: true
  className: "webapprouting.kubernetes.azure.com"
  hosts:
    api: "api.enclaveid.com"
    frontend: "app.enclaveid.com"
