{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "enclaveid.fullname" . }}-ingress
  labels:
    {{- include "enclaveid.labels" . | nindent 4 }}
  annotations:
    kubernetes.azure.com/tls-cert-keyvault-uri: https://enclaveid-cluster.vault.azure.net/certificates/enclaveid-cluster-ingress
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.hosts.api }}
    - {{ .Values.ingress.hosts.frontend }}
    secretName: keyvault-{{ include "enclaveid.fullname" . }}-ingress
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.api }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "enclaveid.fullname" . }}-api
              port:
                number: {{ .Values.api.service.port }}
    - host: {{ .Values.ingress.hosts.frontend }}
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ include "enclaveid.fullname" . }}-frontend
              port:
                number: {{ .Values.frontend.service.port }}
{{- end -}}
