apiVersion: v1
kind: Secret
metadata:
  name: dagster-cloud-agent-token
type: Opaque
data:
  DAGSTER_CLOUD_AGENT_TOKEN: {{ .Values.dagsterSecretValues.DAGSTER_CLOUD_AGENT_TOKEN | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
type: Opaque
data:
  {{ range $key, $value := .Values.apiSecretValues }}
  {{ $key }}: {{ $value | b64enc }}
  {{ end }}
