# TODO: it would be nice to use nvcr.io/nvidia/pytorch:24.04-py3 since it comes
# with all the stuff preinstalled, but they use some weird versioning for the packages
# which results in the existing packages being reinstalled.
FROM python:3.11

SHELL ["/bin/bash", "--login","-c"]

WORKDIR /app

# Install prod dependencies
COPY requirements.prod.txt /app/
RUN pip install --no-cache-dir -r requirements.prod.txt

# Install the root only
COPY dist/ /app/
RUN pip install --no-deps  *.whl

ARG VLLM_IMAGE_NAME
ARG RAPIDS_IMAGE_NAME

ENV VLLM_IMAGE=${VLLM_IMAGE_NAME}
ENV RAPIDS_IMAGE=${RAPIDS_IMAGE_NAME}
