FROM nvidia/cuda:12.6.1-cudnn-runtime-ubuntu24.04

SHELL ["/bin/bash", "--login","-c"]

WORKDIR /app

# install pip
RUN apt-get update && apt-get install -y python3-pip
RUN pip3 install --upgrade pip

# Install VLLM dependencies
COPY requirements.vllm.txt /app/
RUN pip install --no-cache-dir -r requirements.vllm.txt

# TODO: install flashinfer like this for now but we should add it to poetry
RUN pip install flashinfer==0.1.6 -i https://flashinfer.ai/whl/cu121/torch2.4/

# Install prod dependencies
COPY requirements.prod.txt /app/
RUN pip install --no-cache-dir -r requirements.prod.txt

# Install the root only
COPY dist/ /app/
RUN pip install --no-deps  *.whl

ENV HF_HOME=/model-cache/huggingface
ENV SENTENCE_TRANSFORMERS_HOME=/model-cache/sentence-transformers
ENV MKL_THREADING_LAYER=GNU
