# TODO: it would be nice to use nvcr.io/nvidia/pytorch:24.04-py3 since it comes
# with all the stuff preinstalled, but they use some weird versioning for the packages
# which results in the included packages being reinstalled

FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime

SHELL ["/bin/bash", "--login","-c"]

WORKDIR /app

# Update package list and install wget
RUN apt-get update && apt-get install -y wget

# Download and install pip
RUN wget https://bootstrap.pypa.io/get-pip.py
RUN python3 get-pip.py

# Install VLLM dependencies
COPY requirements.vllm.txt /app/
RUN pip install --no-cache-dir -r requirements.vllm.txt

# Install prod dependencies
COPY requirements.prod.txt /app/
RUN pip install --no-cache-dir -r requirements.prod.txt

# Install the root only
COPY dist/ /app/
RUN pip install --no-deps  *.whl

ENV HF_HOME=/model-cache/huggingface
ENV SENTENCE_TRANSFORMERS_HOME=/model-cache/sentence-transformers
ENV MKL_THREADING_LAYER=GNU
