# In dev we save secrets to disk instead of AKV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: {{ .Release.Name }}-model-cache-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 256Gi
#   storageClassName: ultra-disk-sc
#   volumeAttributes:
#     cachingMode: ReadOnly
