name: CI
on:
  push:
    branches:
      - master

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: Jayllyz/free-disk-space@18c3e586e6c1b4d4e68c29fee0748064bd8ee52c
        with:
          # This might remove tools that are actually needed, if set to "true" but frees about 6 GB
          tool-cache: true
          # This one is too slow for the amount of space it frees
          large-packages: true

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_GITHUB_TOKEN }}
          submodules: true

      - name: Install Buildah
        run: |
          sudo apt-get update
          sudo apt-get install -y buildah

      - name: Authenticate Buildah
        env:
          REGISTRY_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo $REGISTRY_PASSWORD | buildah login -u $REGISTRY_USERNAME --password-stdin docker.io

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v3

      - name: Install dasel
        run: curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel

      - uses: actions/cache@v4
        name: Cache for werf manifests
        with:
          key: werf-cache
          path: ~/.werf/

      - name: Install bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

        #TODO use nx affected to only build the projects that have changed
      - name: Build projects
        run: |
          bun nx run backend:build
          bun nx run api:copy-prisma-client
          bun nx run api:build
          bun nx run spa-frontend:build
          bun nx run data-pipeline:build

      - name: Install werf
        uses: werf/actions/install@v2

      - name: Configure Git for werf
        run: |
          git config --global url."https://x-access-token:${{ secrets.PAT_GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Set env variables
        run: |
          echo "WERF_ENV=production" >> $GITHUB_ENV
          echo "WERF_KUBECONFIG_BASE64=${{ secrets.KUBECONFIG_BASE64 }}" >> $GITHUB_ENV
          echo "WERF_SECRET_KEY=${{ secrets.WERF_SECRET_KEY }}" >> $GITHUB_ENV
          echo "WERF_BUILDAH_MODE=auto" >> $GITHUB_ENV
          echo "WERF_REPO_DOCKER_HUB_PASSWORD=${{ secrets.DOCKERHUB_TOKEN }}" >> $GITHUB_ENV
          echo "WERF_REPO_DOCKER_HUB_USERNAME=${{ vars.DOCKERHUB_USERNAME }}" >> $GITHUB_ENV
          echo "WERF_LOG_VERBOSE=true" >> $GITHUB_ENV
          echo "WERF_ALLOWED_LOCAL_CACHE_VOLUME_USAGE=100" >> $GITHUB_ENV
          echo "WERF_REPO=docker.io/enclaveid/cluster" >> $GITHUB_ENV
          echo "WERF_SECRET_VALUES_ENV=k8s/basic/secret-values/secret-values.yaml" >> $GITHUB_ENV

      - name: werf converge
        run: |
          source "$(werf ci-env github --as-file)"
          werf converge --save-build-report
          du -sh ~/.werf/*

      - name: Set data-pipeline-base image value in dagster_cloud.yaml
        run: |
          cat .werf-build-report.json
          DATA_PIPELINE_IMAGE_VALUE=$(./dasel -r json -f .werf-build-report.json '.Images.data-pipeline-base.DockerImageName')
          ./dasel put -r yaml -t string -v $DATA_PIPELINE_IMAGE_VALUE  -f apps/data-pipeline/dagster_cloud.yaml ".locations.first().image"

      - name: Decrypt DAGSTER_CLOUD_AGENT_TOKEN and sync Dagster Cloud locations
        run: |
          DAGSTER_CLOUD_API_TOKEN=$(./dasel -r yaml -f $WERF_SECRET_VALUES_ENV ".dagsterSecretValues.DAGSTER_CLOUD_AGENT_TOKEN" | werf helm secret decrypt)
          pip install dagster-cloud
          dagster-cloud deployment sync-locations \
            -w apps/data-pipeline/dagster_cloud.yaml \
            --api-token $DAGSTER_CLOUD_API_TOKEN \
            --organization enclaveid \
            --deployment prod
